---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: catalog-secret
  namespace: ecommerce-staging
spec:
  encryptedData:
    CATALOG_DB_PASSWORD: AgBJFQn8NFNCQ/F6M50YLUlScexyxG9GvsuBxxW4jQmWjA+BBw/pwyqOzBv0dZ01IrIkqTWhr+dfHbt7FCjHSQ/EMUWZKo39jy3poJJluQ8N+U9KlgA4wJVBrx36e62Gt3DUqQSF5qnSb92cF+3fMBONyQwJzsqPwCNMpX2EoePpP7Mic58I2el3YoJT/q7z3FIesoZXPY+pe/jh7X4vR8L/a4dZ9ryTmGiT7kuwlPMw5N2/vWvRyXs9UuDNJvGU4NxlH/Tu4oNQX0n+cG89dyUAhZiQLAjzUu4Y2YqsNfXLZsw3sIQbwRXHVjdJoU8o6ACcv+RRWGgqyFHDv2cEkxLBEp5v6yskKreVAAHYzYgXXsxOE8bsRt0XF1jszC83cg5lcNWl9a4CNJjdFHd72o53Y0+0AHI7cN7dyrElHa8mLcu3bJJLhtKuRuQCElabqzeOiGSgY7s0bkF18OjmWv8UDXbb4apqz26usTRWzN2wBn4bivuNLBqTthIY2npm0gfEXxeesvEl8snTKPeTEy69SM0IDFlXkMI0DYP0sROITfDwIgrHFlvvOUsBUk/wZuK0H/1UHB6ikaof8Y1nF8YNW1vIOp4QWW+bzLJdNa6hgBt1NDfW5x+Ua1e6vQa+XnSLPk7FuVsjnDlaGr8JAJjPZVX/OxXVdKZLkp50m2BhjN9gLv8tmFSJx2Bwf8iL7nK83vW+yyWaW0mx8KtBRbkW+5+TbLB0BgfrfEFUNsTWJQ==
  template:
    metadata:
      name: catalog-secret
      namespace: ecommerce-staging
