---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inventory-secret
  namespace: ecommerce
spec:
  encryptedData:
    INVENTORY_DB_PASSWORD: AgDANlzgMdEcojHJPW5hNrzF7j103Lf7cIfIUQ1Td6eG5Om48I2TEPCKhd8kxs2PTq/13hOYamfJ93k7cFBVlHNsY7dAsVS0A3iD7Twx9bLLg1PkFlWUXWy2EgHtFEgdOtemGW5tiKu5k89M0uf966J7zWOtwooBMDUqRMIXUSyWVZtR9Ttm1goeXJmXj5udlflZOXiVDgLDbxvjoFJbshoOdR8DA0OTM+Bo4dj0mNLT9N2TWTw7MVhtJ0xxDqZ5Zsyi951e5hN5+7ntJdSlfU3FMKxtlUrIUht57Fpevih7kfjO6m/fnvzMK+k78W/GWLi2WJOkxfWhf8VAnNNydfgqEkvh/LWpTZ+z0X+wyXV0TXeohhHETWhgYeSX5S3yC5RPpJ1SobRw5UGYtfuZGIJ/irpYIF83+pVGkJhkkPZgL+vKyYSEuKEqycYK4XWgHbnU2ZxBG/9VxcI8BFWSkBCGSMijeq9iIiqQMjnWAlY87u5xikfFWpBytopMlcX7L7OludhnsJC7oGNuGOJ6eidaJe2OI7L2FBKWcG2Mkatgt37WkZVMl+WQIdl8zwtkz3xmt1Lbmu/tQCOFTakbPZC3VmC62s1VOirh0MOMhx6EZydc2W8ueoFMmHCsdBxTCEoG2SEgvaN1B9IulgNcPtVW0aKbFRfNA5YO+im4pltEjNCIu3JtuB0mGfvtk2cGOFM7YAOhFx2Ct5mHErSWWAOahPu/JPWr9xn/dXeDC0Z/yA==
  template:
    metadata:
      name: inventory-secret
      namespace: ecommerce
