---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: catalog-secret
  namespace: ecommerce
spec:
  encryptedData:
    CATALOG_DB_PASSWORD: AgDJ8ZJiCzCsNucUY2etOmvvkY1/2Ic+a1b5EwEZ2guklGwGlV1d+r721QiRC5RJN/x6PFM1++gyWgWOc85bWRoEySWpHIoa9S1zal38Avx7fs+eNSBj60ptDA34uR2uYyKos7XeecSBw6Jcd3KKtYyH/7qSjETRYGUameKs7g3QJFPFGha59CjcF0UUjuI8IOrh9eyON4hHK1Gkpa0Zdyz/zKqqScNYTnkiAEGldLvT491y7lZhEmM9v4Dg6g0GSP6pJ1dDidQux6P/+tInypv8Zzk9HicF54Z3kCWGpxOgpS49oQ+2QJaX/5rfdkqDwbpoT7vMHZ5HS+7RWFOh1MgWCllbsUMPcQGUOGCDBv+z2t4/g7VW2H/MHF5Rlqt4GwElpLCFJExhZaaxK7quP3PzDCcTIrizuzncMOSrX8WuhFVXdQl10Lv+xY/RoboPfLIKV/y5tMqjrv9w2Nq1zw8wcxjew8uwMNBQ9Q3U8gZLccLW+YwDb71V8u+JSAO4nHo/WpB0XnE2Gk7k9qC+WLngrTY8poLyQ5MfJ2G5VicFL7JeSl/EcBD5DBHBd4Ka6qgFQ+XscuG7Cg57+0/H9DBk2YRN/2RSG/W6v3Cl4yqTVg/EXeujQQeA796v7SgVYZM4haegmYGLaLggidQpnQGoVQmgYN1Up+hpqFXe5ZxZiYQpdc9y3zjIIRtKkc5Ty20PTzpcjjJdYhtl1YmLXy5OUB5oDtUh7614r2ij8HKX8w==
  template:
    metadata:
      name: catalog-secret
      namespace: ecommerce
