---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: ecommerce-staging
spec:
  encryptedData:
    credentials.json: AgBPMzRBYntQiu+m07IYbPcMWyQiodfBs+XcUsyHp1itbugN9XCEj25aP63FFQg+Hs0ldfdDWT39m11ebWmgtzm6pv2jjTFnoGuYSgohLUTt6qFOSxi1tVUgSgSiLf8DEV8+rF6f9c6pBnqlSXpy4kB4XzlBKOhGjHbyXOwg8VVVkzKGH+ttBsr5DNV3ISz1rquRLAxUB4mpuHwGL5Nfuj+QQVDYJmQdVf6DaD8K4n5v6WxBhXhZxwYJd+SsErL4kRlz1VTSSpTnqQnAbuyt7VjWUAU7UIEWMq/UxwMAIWO5Cd0Trl55jOyNJdoGbrp87Dlhz5wBvsDLxVXNqo2ifLPygkk0hWizweYNKY9tqhd2M2STglCtKrnvPSIA1ZjB1CfZzNCfZ0ujD40KW65DmV18gdsVI3doTdF3ZImxQr4omwbZkZG27sxiCP30K76sAHHIv/mtSWyf8S4ZvvcycQLkMdPE45vVJHKXdEfHvdyPlBUgfMO5UH19OHb6G1vb7ChwglwO2SoHLwSbZiiLMxzLEkcaGAI61+LnFThIyUmnaofDsU5UL2loYW4NOhjekhzgG42qIREgwMHpMjrbn13p9XQxtgCbu9mje8moD9IM9HEgV8YM8EGA1foVwkdVpyfFmJvyBm/QYd+MNnsswDf2wPHRyDcfPsFK/sy11cObaVNuAEkLTkVxKi23XcUHdwxBDBy1Xp+KVplVHDNRreb2D84MxoTCEgFrGHFU0j8tSGUvMdsdRR1We7b8kXaeek4LUTiAiW74parVOtrpgPk+yaE5/t2shm6PjbMFOVwtLqtHNCGQVr4mokizMCUebdDUs+ASOoIzGquRdTwPGi3bcLRp6DVJUTZZC9iVDcudBBBmOFXYSEdpDlIxWaYaLhCUC3M2iSNerQ+iJWhfgjZoLqQmizCGnuAMfw2zPh/a
  template:
    metadata:
      name: cloudflared-credentials
      namespace: ecommerce-staging
