---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inventory-secret
  namespace: ecommerce-staging
spec:
  encryptedData:
    INVENTORY_DB_PASSWORD: AgBOrmv7Bgpvf3E+O9qNU/HhINgPE+PjAJasbyEv0FfHtLA22nqe2qgFfSTp4hkLmcvxHLpQNhTvgZunhqMK/KoNlaoziCHRo31/PdjVewo50aVQhvo9Vb0x9ljE8XwCsy3GQFCxnEVfqUdyipOdn4VGVRmqmvTna2FL4Wvodaxnxoqd5w9PAjlrewT5TSWUCzcrfKbZs3iKGIAAoA5/NsqWRYJfvznsPNiBrtM9p6DLs4sjDCDTGAg1m3wOX1gfxDXP26i1rmP887L3vm/DsqsLb9WRuRWQsVBQtS8c4J3hGz9h+Er5Zge2vCo00ihPoA+apEJaoVdM+3J4r/i3H7kZkj4PMFwav/US2ifvD4uUFv1UPmiRcMNE/epBH6603foUAi5fHas5+rHDAhmsona2mHKYx3MvGIRgIUAhFTSWURgpix3sqtSgdfLSqgM1yaSkIx90/ppd+2tDUPJhBJllTXzshEZAYR5SShifX/L49sgxVxS1Ry1Z9d5C5aBeuxbCZcvoROyZsZRGjFI8GPPd7KWGYobDgKevdkCGebIDovrJQhwZbasorrdkf+ANeuZErJGyzefPfxpqpT7MGw7pqlPfVFJo4lzsqLCza0Df1ERxZHGy0el8hOQlSka3OxOmFHeWFZ0xvCWWz2OZDrNd5+MqLlTQi3e1qbcCs/qMTHKLMOQ1S01C61muJSaIytqTa7SRcdnA6iCZn7ySYOZPzZrwh+V6BRDLf/ckr69JDA==
  template:
    metadata:
      name: inventory-secret
      namespace: ecommerce-staging
