---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: ecommerce
spec:
  encryptedData:
    credentials.json: AgDQTBFR+BePMIcaxUVwrwi2wAO9rPx6M2tfSyPcEzeXWSMpU9CGtRgxOmhFldU+uI42H/GoeynpFgT/H9SYZ5IbeS3rNtfxld3sFZ/RgzIiXnHy9kCUoRGHFrg82sun9Mq4dFlVftfJ3zOAYNH28wef91Uci+eJgqFrPl8VeIyTn9LCBFPcTMrMxK17b/3fOXqc3ZfinPBfb9YHzKA6JKyyE22I78Xkq9y7YzPeDdpOfNY+mAjvIGSHSeI3tv/ecF70gwLk1QYfKSA/2DRRPtNoefOzKfdcYO0pRVcGfXrem4S6+k7WNnXv6H8uFVBrf/aF5tDcG3gYO8JzXHCX2/W64FFldXjLoEH0GhmbT35STgReb7iXZjKJzOYf2u00yIBzNkNjnHJUS30myqcSS+jivr7j3JYlIHSIFy7sj+FzGyCgOi7kJ9cCffrtIrkmSxtMxez65ZF9BT/zMBXQ1hIfMeE6YQTwuNAIi9Y2j7/VaNLtvqTYX70FNZTNG9gny1MVcWEWY5HBYplyAyBsp/YkJJQEQhIanVro4NhYqUKh+ptKeb1RrTYydCS0U/YQBe8N5txjFMS4cGfdKDWIW8z+uKH2AeJQiH7vXqiFdPlqV28JnOlpNoR2f1Im8rBetb5wy3eUNvGcn9KAgIR2r5AX6v2TIX1ahDWqrN1w7Y6grVIn+HliurZCw8Ibfs+sJmnMuEh8evNmVnGqx/HwE867AP7eyNbKDl3cGdp4W9HOUmd1mkxUG2LOkUwpghMsR3V9vy7Fl0eFZqJhhfsXAv11vx6ZV1kBUFPiwuC8nc5AfWjyTvNbe58W7cbYbqJlcjqzAj3vFr1fR/XB1+XGWVAbtWc4ISFfBcsxFTMcym/o9b6BbjYIyTPklQ9YbpaOznb2jTprRiP0NRjlZsslyQPEcwMNP2Pd+6ZYpNpIYkvR
  template:
    metadata:
      name: cloudflared-credentials
      namespace: ecommerce
